"""ubah schema & hapus id di table user

Revision ID: 2029507eb083
Revises: beaf38b8fc70
Create Date: 2025-10-14 20:33:56.735870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2029507eb083'
down_revision: Union[str, Sequence[str], None] = 'beaf38b8fc70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'nik',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_nik'), table_name='users')
    op.create_index(op.f('ix_users_nik'), 'users', ['nik'], unique=False)
    op.create_index(op.f('ix_users_nama'), 'users', ['nama'], unique=True)
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_users_nama'), table_name='users')
    op.drop_index(op.f('ix_users_nik'), table_name='users')
    op.create_index(op.f('ix_users_nik'), 'users', ['nik'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'nik',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
