"""ubah schema & hapus id di table user

Revision ID: 42bb3147237e
Revises: 2029507eb083
Create Date: 2025-10-14 20:41:44.396083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42bb3147237e'
down_revision: Union[str, Sequence[str], None] = '2029507eb083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_primary_key("pk_users", "users", ["nik"])
    
    op.create_table('gizi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nik', sa.String(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('status_bmi', sa.String(), nullable=True),
    sa.Column('kalori_harian', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nik'], ['users.nik'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gizi_id'), 'gizi', ['id'], unique=False)
    op.create_index(op.f('ix_gizi_nik'), 'gizi', ['nik'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gizi_nik'), table_name='gizi')
    op.drop_index(op.f('ix_gizi_id'), table_name='gizi')
    op.drop_table('gizi')
    # ### end Alembic commands ###
