"""tambah table gizi

Revision ID: beaf38b8fc70
Revises: c5597a9c3c53
Create Date: 2025-10-14 20:10:28.552831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beaf38b8fc70'
down_revision: Union[str, Sequence[str], None] = 'c5597a9c3c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gizi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nik', sa.String(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('status_bmi', sa.String(), nullable=True),
    sa.Column('kalori_harian', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nik'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gizi_id'), 'gizi', ['id'], unique=False)
    op.create_index(op.f('ix_gizi_nik'), 'gizi', ['nik'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_gizi_nik'), table_name='gizi')
    # op.drop_index(op.f('ix_gizi_id'), table_name='gizi')
    # op.drop_table('gizi')
    # ### end Alembic commands ###
