"""tambah table gizi

Revision ID: c5597a9c3c53
Revises: d7148dc4fed5
Create Date: 2025-10-14 19:54:18.976843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5597a9c3c53'
down_revision: Union[str, Sequence[str], None] = 'd7148dc4fed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_nama'), 'users', ['nama'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_nama'), table_name='users')
    # ### end Alembic commands ###
