"""Initial migration

Revision ID: d5d471e51779
Revises: 
Create Date: 2025-10-16 16:36:10.280491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5d471e51779'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TYPE IF EXISTS statusenum')
    op.execute('DROP TYPE IF EXISTS pal')
    op.create_table('users',
    sa.Column('nik', sa.String(), nullable=False),
    sa.Column('nama', sa.String(), nullable=True),
    sa.Column('usia', sa.Integer(), nullable=True),
    sa.Column('tempat_lahir', sa.String(), nullable=True),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('tanggal_kehamilan_pertama', sa.Date(), nullable=True),
    sa.Column('pal', sa.Enum('sedentary', 'lightly_active', 'moderately_active', 'very_active', 'super_active', name='pal'), nullable=True),
    sa.Column('alamat', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('berat_badan', sa.Float(), nullable=True),
    sa.Column('tinggi_badan', sa.Float(), nullable=True),
    sa.Column('lingkar_lengan_atas', sa.Float(), nullable=True),
    sa.Column('periode_kehamilan', sa.Enum('trisemester1', 'trisemester2', 'trisemester3', 'postsemester', name='statusenum'), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('nik')
    )
    op.create_index(op.f('ix_users_nama'), 'users', ['nama'], unique=True)
    op.create_index(op.f('ix_users_nik'), 'users', ['nik'], unique=False)
    op.create_table('gizi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nik', sa.String(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('status_bmi', sa.String(), nullable=True),
    sa.Column('kalori_harian', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nik'], ['users.nik'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gizi_id'), 'gizi', ['id'], unique=False)
    op.create_index(op.f('ix_gizi_nik'), 'gizi', ['nik'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gizi_nik'), table_name='gizi')
    op.drop_index(op.f('ix_gizi_id'), table_name='gizi')
    op.drop_table('gizi')
    op.drop_index(op.f('ix_users_nik'), table_name='users')
    op.drop_index(op.f('ix_users_nama'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
