"""Create users table

Revision ID: d7148dc4fed5
Revises: 
Create Date: 2025-10-02 19:25:47.069807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7148dc4fed5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nik', sa.String(), nullable=True),
    sa.Column('nama', sa.String(), nullable=True),
    sa.Column('usia', sa.Integer(), nullable=True),
    sa.Column('tempat_lahir', sa.String(), nullable=True),
    sa.Column('tanggal_lahir', sa.String(), nullable=True),
    sa.Column('alamat', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('berat_badan', sa.Float(), nullable=True),
    sa.Column('tinggi_badan', sa.Float(), nullable=True),
    sa.Column('lingkar_tangan', sa.Float(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_nik'), 'users', ['nik'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_nik'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
